name: rtdvenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - scipy
  - numpy
  - matplotlib
  - sympy
  - pip:
    - sphinx-autodoc-typehints
    - gitpython
    - better-apidoc
    - nbsphinx
